package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"github.com/magodo/terraform-provider-azurerm-insight/pkg/core"
	"io"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
)

func main() {
	flag.Usage = func() {
		fmt.Fprint(os.Stderr, "Generate terraform schema file for later adding links to swagger schema.\n\n")
		flag.PrintDefaults()
		os.Exit(2)
	}

	pwd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	providerSchemaPath := flag.String("provider-schema", "", `The path to the Terraform provider schema file (generated by "$ terraform providers schema -json")`)
	providerName := flag.String("provider-name", "", "Full qualified name of the provider (e.g. registry.terraform.io/hashicorp/azurerm)")
	outputPath := flag.String("output", pwd, "The output directory")
	resource := flag.String("resource", "", "The Terraform resource name which to generate its flattened schema scaffold. If not specified, will apply to all resources available.")
	isDataSource := flag.Bool("data-source", false, "Whether applies to data source")
	showHelp := flag.Bool("help", false, "Display this message")

	flag.Parse()

	if *showHelp {
		flag.Usage()
		return
	}

	// Read the provider schema
	b, err := ioutil.ReadFile(*providerSchemaPath)
	if err != nil {
		log.Fatal(err)
	}

	var providerSchemas core.TerraformProviderSchemas
	if err := json.Unmarshal(b, &providerSchemas); err != nil {
		log.Fatal(err)
	}

	provider, ok := providerSchemas.Schemas[*providerName]
	if !ok {
		log.Fatalf("Provider: %s not found in the provider schemas", *providerName)
	}

	// Prepare output directory
	if err := os.MkdirAll(*outputPath, 0755); err != nil {
		log.Fatal(err)
	}

	if *resource != "" {
		var (
			ok     bool
			prefix string
			schema *core.TerraformSchema
		)
		if *isDataSource {
			schema, ok = provider.DataSourceSchemas[*resource]
			if !ok {
				log.Fatalf("No such data source: %s", *resource)
			}
			prefix = "data_"
		} else {
			schema, ok = provider.ResourceSchemas[*resource]
			if !ok {
				log.Fatalf("No such resource: %s", *resource)
			}
		}
		ofile := filepath.Join(*outputPath, prefix+*resource)
		if err := genFile(prefix+*resource, schema.Block, ofile); err != nil {
			log.Fatal(err)
		}
		return
	}

	var (
		schemas map[string]*core.TerraformSchema
		oprefix string
	)
	if *isDataSource {
		schemas = provider.DataSourceSchemas
		oprefix = "data_"
	} else {
		schemas = provider.ResourceSchemas
	}

	for res, schema := range schemas {
		ofile := filepath.Join(*outputPath, oprefix+res)
		if err := genFile(oprefix+res, schema.Block, ofile); err != nil {
			log.Fatal(err)
		}
	}
	return
}

func genFile(schemaName string, blk *core.TerraformBlock, ofileBase string) error {
	schema := core.NewSchemaScaffoldFromTerraformBlock(schemaName, blk)
	b, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return err
	}

	ofile := ofileBase + ".json"
	ofileBkp := ofileBase + ".json.bkp"

	// backup file if exists
	if stat, err := os.Stat(ofile); err == nil && stat.Mode().IsRegular() {
		src, err := os.Open(ofile)
		if err != nil {
			return err
		}

		dst, err := os.Create(ofileBkp)
		if err != nil {
			return err
		}

		if _, err := io.Copy(dst, src); err != nil {
			return err
		}
	}

	if err := ioutil.WriteFile(ofile, b, 0644); err != nil {
		return err
	}
	return nil

}
